version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: smart-clinic-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_clinic_db
    ports:
      - "23306:3306"
    volumes:
      - smart-clinic-mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: smart-clinic-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - smart-clinic-mongodb-data:/data/db

volumes:
  smart-clinic-mysql-data:
  smart-clinic-mongodb-data: